- include_vars: credentials.yml
- name: Provision EC2 instance
  ec2:
    image: ami-47a23a30
    instance_type: t2.micro
    region: eu-west-1
    key_name: AY-ELK
    wait: True
    count: 5
    volumes:
      - device_name: /dev/sda1
        delete_on_termination: True
        volume_size: 8
  register: ec2
- name: Add instance to host group
  add_host: hostname={{ item.public_ip  }} groupname=monitor_farm
  with_items: ec2.instances
- name: Wait for SSH to be available
  wait_for: host={{ item.public_ip }} port=22 delay=15 timeout=320 state=started
  with_items: ec2.instances

