- name: Install nrpe server
  apt: name=nagios-nrpe-server state=present
- name: Install nagios-plugins
  apt: name=nagios-plugins state=present
- name: Copy nrpe config
  template: src=nrpe_local.cfg dest=/etc/nagios/nrpe_local.cfg
- name: Restart nrpe server
  service: name=nagios-nrpe-server state=restarted
- name: Touch log
  command: touch /home/ubuntu/app.log
- name: Chmod log
  command: chmod 0777 /home/ubuntu/app.log
- name: Install nginx
  apt: name=nginx state=present
- name: Install logstash
  apt: name=logstash state=latest force=yes
- name: copy logstash conf 10
  template: src=10-syslog.conf dest=/etc/logstash/conf.d/10-syslog.conf
- name: copy logstash conf 20 
  template: src=30-output.conf dest=/etc/logstash/conf.d/30-output.conf
- name: copy logstash conf 30
  template: src=20-filter.conf dest=/etc/logstash/conf.d/20-filter.conf
- name: Set default acls for logs
  acl: name=/var/log entity=logstash etype=user permissions="r" default=yes state=present
- name: Set acl for auth.log
  acl: name=/var/log/auth.log entity=logstash etype=user permissions="r" state=present
- name: Set acl for syslog
  acl: name=/var/log/syslog entity=logstash etype=user permissions="r" state=present
- name: Set default acls for nginx directory for new logs
  acl: name=/var/log/nginx entity=logstash etype=user permissions="rwx" default=yes state=present
- name: Set default acls for nginx directory
  acl: name=/var/log/nginx entity=logstash etype=user permissions="rwx" state=present
- name: Set acl for access.log
  acl: name=/var/log/nginx/access.log entity=logstash etype=user permissions="r" state=present
- name: Set acl for error.log
  acl: name=/var/log/nginx/error.log entity=logstash etype=user permissions="r" state=present
- name: copy application
  template: src=app.py dest=/home/ubuntu/app.py
- name: set acl  for app.py
  acl: name=/home/ubuntu/app.py entity=ubuntu etype=user permissions="rwx" state=present
- name: nginx conf
  template: src=nginx.conf dest=/etc/nginx/sites-available/default
- name: Restart nginx
  service: name=nginx state=restarted
- name: Start logstash service
  service: name=logstash state=restarted enabled=yes
- name: Install pip3
  apt: name=python3-pip state=present
- name: Install flask
  command: pip3 install flask
- name: Install uwsgi-python3
  apt: name=uwsgi-plugin-python3 state=present
- name: Install supervisord
  apt: name=supervisor state=present
- name: Copy supervisor config
  template: src=uwsgi.conf dest=/etc/supervisor/conf.d/uwsgi.conf
- name: Restart supervisor
  service: name=supervisor state=restarted
- name: Install collectd
  apt: name=collectd state=present
- name: Collectd config
  template: src=collectd.conf dest=/etc/collectd/collectd.conf
- name: Restart collectd
  service: name=collectd state=restarted
